### ISSUE TITLE
Regression: Router breaks navigation to custom home URL

### ISSUE THREAD

**Issue by elringus** [vuejs/vitepress#3264]
### Describe the bug

When using custom home page and `themeConfig.logoLink` is set to that paget, after any navigation happens in the docs, clicking the logo loads 404 page. See video below for a demo.

https://github.com/vuejs/vitepress/assets/2056864/69241914-58ab-4400-9013-7d9379cb4c14

### Reproduction

Not sure how reproduce this in a sandbox (the docs have to be deployed), but here are the sources of the demo above: https://github.com/naninovel/Documentation/tree/master/docs

Notice, that the bug only kicks in after some navigation happens in the docs; eg, it won't reproduce if you open the docs and immediately click the logo (in this case the home page will load correctly).

### Expected behavior

Clicking on logo should load custom home page.

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz
    Memory: 52.30 GB / 63.92 GB
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.29.3 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Chrome: 119.0.6045.160
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.72)
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
should be fixed in vitepress 1.0.0-rc.29

**Comment by elringus** [comment]
I've actually tested this on the latest rc.31 (in a [branch](https://github.com/naninovel/Documentation/tree/feat/optimize)). 

Just to make sure I've updated to 31 on the main branch and deployed — still the same issue.

**Comment by zonemeen** [comment]
Try changing the `logoLink: "https://naninovel.com"` in your configuration to `logoLink: "//naninovel.com"` or `logoLink: "naninovel.com"`.

**Comment by elringus** [comment]
> Try changing the `logoLink: "https://naninovel.com"` in your configuration to `logoLink: "//naninovel.com"` or `logoLink: "naninovel.com"`.

Didn't work: `naniovel.com` in logo link redirects to `https://naninovel.com/guide/naninovel.com` when logo is clicked.

Notice, that I'm using custom `./public/index.html` and don't have `./src/index.md`. Previously it worked fine on deployment and in `preview`, but in `dev` it was returning 404 (which I didn't mind); I remember in some of the recent patches you've mentioned something about making both router in dev and preview work the same, may this is where it regressed (can't find the exact release to test).

**Comment by zonemeen** [comment]
Is it still not working if you set it to `logoLink: "//naninovel.com"`?

The temporary workaround I can think of is this.🤔

**Comment by elringus** [comment]
> Is it still not working if you set it to `logoLink: "//naninovel.com"`?
> 

Nope, still the same behavior.

**Comment by brc-dd** [comment]
Use this in next version:

```ts
    logoLink: {
      link: '/',
      target: '_self'
    },
```

It should work fine in dev too.
